// Types for secrets set via Cloudflare Pages dashboard (not declared in
// wrangler.jsonc because Pages config validation rejects the secrets field).
// TypeScript merges this with the Env interface generated by wrangler types.
interface Env {
  SUPABASE_URL: string;
  SUPABASE_SERVICE_KEY: string;
  RESEND_API_KEY: string;
  STRIPE_SECRET_KEY: string;
}
